// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
 class AutomationCloner {
    public static clone(original: Automation): Automation {
        const clone = new Automation();
        clone.isLinear = original.isLinear;
        clone.type = original.type;
        clone.value = original.value;
        clone.ratioPosition = original.ratioPosition;
        clone.text = original.text;
        return clone;
    }
}
