type topbar.css > wholecss.css
type sizesmall.css >> wholecss.css
type base.css >> wholecss.css
type sampler.css >> wholecss.css
type menu.css >> wholecss.css
type leftbar.css >> wholecss.css
type toolbar.css >> wholecss.css
type mixer.css >> wholecss.css
type timeselect.css >> wholecss.css
type plugin.css >> wholecss.css
type fanpane.css >> wholecss.css
type colordarkred.css >> wholecss.css
type font1small.css >> wholecss.css
