declare function freshSlate(): void;
declare const setAppH: () => void;
declare const ctx: AudioContext;
declare const CURVE: Float32Array<ArrayBuffer>;
declare const NOISE_SECONDS = 2;
declare const NOISE_DATA: Float32Array<ArrayBuffer>;
declare const IR_SECONDS = 1.6;
declare const IR_DATA: Float32Array<ArrayBuffer>[];
declare function fillFrom(dst: any, src: any): void;
type Buss808 = {
    master: GainNode;
    comp: DynamicsCompressorNode;
    makeup: GainNode;
    drive: GainNode;
    post: GainNode;
    dry: GainNode;
    wet: GainNode;
    verb: ConvolverNode;
};
declare function makeBus(ac: AudioContext, offline?: any): Buss808;
declare const bus: Buss808;
declare let activeVoice: Voice808 | null;
declare function trackSource(node: any): any;
type EngineFunc808 = (time: number, out: AudioNode, pitchRatio: number) => void;
type CategoryKit808 = {
    names: string[];
    engineFunctions: EngineFunc808[];
};
type KIT808 = {
    boom: CategoryKit808;
    kick: CategoryKit808;
    snare: CategoryKit808;
    clap: CategoryKit808;
    chat: CategoryKit808;
    cowbell: CategoryKit808;
    ohat: CategoryKit808;
    hitom: CategoryKit808;
};
declare function findKitCategoryByName(kit: KIT808, name: 'boom' | 'kick' | 'snare' | 'clap' | 'chat' | 'cowbell' | 'ohat' | 'hitom'): CategoryKit808;
declare function make808Kit(ac: AudioContext): KIT808;
declare const workGlobalKIT: KIT808;
declare const power: HTMLElement;
declare const powerLabel: HTMLElement;
declare let lastLive: number;
declare let idledTick: boolean;
declare function armShowLabelLive(): void;
declare const GATE: {
    2: number[];
    3: number[];
    4: number[];
    5: number[];
};
declare const loadStore: (key: any) => any;
declare const chokeSettings: any;
declare const pitchSettings: any;
declare const variantSettings: any;
declare const volumeSettings: any;
declare const sendSettings: any;
declare const VOL: {
    '-4': number;
    '-3': number;
    '-2': number;
    '-1': number;
    0: number;
    1: number;
    2: number;
    3: number;
    4: number;
};
declare const SEND_GAIN: {
    0: number;
    1: number;
    2: number;
    3: number;
    4: number;
    5: number;
};
declare const volOf: (name: any) => any;
declare const padSend: {};
declare const variantOf: (name: string) => number;
type Voice808 = {
    vg: GainNode;
    n: number;
    done: boolean;
    timer: number;
};
declare function renderHit(name: string, t: number, vel: number | null): void;
declare function triggerPadSound(name: string, vel: number | null): void;
declare function flash(pad: any, ms?: number): void;
declare function renderMutes(): void;
declare const keymap: {
    a: string;
    s: string;
    d: string;
    f: string;
    q: string;
    w: string;
    e: string;
    r: string;
};
declare const padByVoice: {};
declare function attachDial(pad: any, opts: any): {
    set: (v: any) => void;
    get: () => any;
    min: any;
    max: any;
    id: string;
    text: () => any;
    flashHTML: (html: any) => void;
};
declare const announceEl: HTMLElement | null;
declare let annT: number, annQuiet: boolean;
declare function announce(text: any): void;
declare const dials: any[];
declare const verbSettings: any;
declare const WET: {
    1: number;
    2: number;
    3: number;
    4: number;
    5: number;
};
declare const DRYLVL: {
    1: number;
    2: number;
    3: number;
    4: number;
    5: number;
};
declare const compSettings: any;
declare const COMP: {
    1: number[];
    2: number[];
    3: number[];
    4: number[];
    5: number[];
};
declare const tubeSettings: any;
declare const DRIVE: {
    1: number[];
    2: number[];
    3: number[];
    4: number[];
    5: number[];
};
declare const dialMap: {};
declare const rndDials: any[];
declare const shiftBtn: any;
declare let shiftLatch: boolean, shiftKey: boolean, shifted: boolean;
declare function applyShift(): void;
declare const rndBtn: any;
declare const rndHap: HTMLInputElement;
declare const rndBanks: any;
declare const placeHap: () => void;
declare let pendingKit: any;
declare function applyKit(vals: any): void;
declare const rollAll: () => void;
declare const DIE_COLORS: string[];
declare let dieC: number;
declare const rootStyle: CSSStyleDeclaration;
declare const flipEl: any;
declare const FB: {
    v: unknown[];
    h: unknown[];
    d: unknown[];
};
declare const ROLLS: (string | number)[][];
declare let fbCur: any;
declare let fbRaf: number;
declare const tStore: any;
type Event808 = {
    pad: string;
    beat: number;
    v: number;
};
type Auto808 = {
    id: string;
    beat: number;
    v: number;
};
type Seq808 = {
    bpm: number;
    quant: number;
    swing: number;
    mutes: {};
    metro: boolean;
    guess: boolean;
    playing: boolean;
    recording: boolean;
    events: Event808[];
    auto: Auto808[];
    bars: number;
};
declare const seq: Seq808;
declare const saveT: () => void;
declare const spb: () => number;
type SuppressHit808 = {
    pad: string;
    t: number;
    v: number;
};
type GuessTime808 = {
    pad: string;
    t: number;
    v: number;
};
declare let recStart: number;
declare let passStart: number;
declare let evIdx: number;
declare let sched: any[];
declare let suppressHit: SuppressHit808 | null;
declare let autoIdx: number;
declare let autoSched: any[];
declare let applyingAuto: boolean;
declare let guessTimes: GuessTime808[];
declare let guessAuto: any[];
declare const touchedIds: Set<unknown>;
declare let metroAnchor: number, metroBeat: number;
declare const recBtn: any;
declare const trashBtn: any;
declare const playBtn: any;
declare const metroBtn: any;
declare const quantBtn: any;
declare const bpmEl: any;
declare const bpmVal: any;
declare const countEl: any;
declare const wavBtn: any;
declare let losto: any;
declare let wavBits: number, wavRate: number;
declare const linkBtn: any;
declare const midBtn: any;
declare const laneEl: any;
declare const undoBtn: any;
declare const undoStack: any[];
declare function pushUndo(): void;
declare function doUndo(): void;
declare function renderCount(): void;
declare function renderTransport(): void;
declare function clickTone(t: any, accent: any): void;
declare const qBeat: (beat: any) => any;
declare function buildSched(): void;
declare function buildAutoSched(): void;
declare function seekAuto(): void;
declare function onDialWrite(id: any, v: any): void;
declare function guessBpm(rel: any): any;
declare function seekSched(): void;
declare function startRec(): void;
declare function stopRec(): void;
declare function startPlay(): void;
declare function setBpm(nv: any): void;
declare function swingName(v: any): string;
declare function queueSwing(target: any): void;
declare let bpmY: number, bpmFrom: number, bpmMoved: boolean;
declare function editBpm(): void;
declare const banks: any;
declare let armSave: boolean;
declare let activeSlot: null;
declare let pendingSlot: null;
declare let switchAt: number;
declare let pendingSwing: null;
declare let swingAt: number;
declare const banksEl: any;
declare const saveBtn: any;
declare const slotBtns: Element[];
declare const saveBanks: () => void;
declare function renderBanks(): void;
declare function saveSlot(i: any): void;
declare function applySlot(i: any): void;
declare function loadSlot(i: any): void;
declare function encodeWav(chs: any, rate: any, bits: any): Blob;
declare const clampInt: (v: any, lo: any, hi: any, def: any) => any;
declare function exportWav(): Promise<void>;
declare let pendingWav: any;
declare const wavSheet: HTMLElement | null;
declare const wavGoBtn: any;
declare const wbits16: HTMLElement | null;
declare const wbits24: HTMLElement | null;
declare const wrateNative: HTMLElement | null;
declare const wrate441: HTMLElement | null;
declare const wavMsgEl: HTMLElement | null;
declare let wavOpener: any;
declare function wavSay(t: any, bad?: any): void;
declare function resetWavGo(): void;
declare function renderWavOpts(): void;
declare function openWavSheet(): void;
declare function closeWavSheet(): void;
declare function setWavBits(b: any): void;
declare function setWavRate(r: any): void;
declare function saveWav(): Promise<void>;
declare function resampleChannels(chans: any, srcRate: any, dstRate: any): Promise<any>;
declare const SHARE_API = "https://808-share.mullinsben.workers.dev";
declare const PADS: string[];
declare const b64u: {
    enc: (s: any) => string;
    dec: (s: any) => string;
};
declare const r3: (x: any) => number;
declare const encEvents: (evs: any) => any;
declare const encAuto: (au: any) => any;
declare const decEvents: (arr: any) => any;
declare const decAuto: (arr: any) => any;
declare function buildLoopPayload(): {
    v: number;
    t: number;
    b: number;
    e: any;
    a: any;
    s: {};
    k: (0 | {
        b: any;
        e: any;
        a: any;
        s: any;
    })[];
};
declare function applyLoopPayload(d: any): boolean;
declare function loadHashLoop(): void;
declare function codeFrom(text: any): any;
declare function loadCode(code: any): Promise<boolean>;
declare function mintCode(): Promise<any>;
declare function linkNope(el: any): void;
declare function execCopy(text: any): boolean;
declare function copyText(text: any, okFn: any, noFn: any): void;
declare const sheet: any;
declare const sheetURL: any;
declare const sheetCopy: HTMLElement | null;
declare const sheetShare: HTMLElement | null;
declare const sheetMint: HTMLElement | null;
declare const sheetEmpty: HTMLElement | null;
declare const loadInput: any;
declare const loadBtn: HTMLElement | null;
declare const sheetMsg: HTMLElement | null;
declare let currentURL: string;
declare const sheetSay: (t: any, bad?: any) => void;
declare let sheetOpener: any;
declare function openSheet(): void;
declare function closeSheet(): void;
declare function sheetFocusables(): any;
declare function doLoad(): void;
declare const unlockEvents: string[];
declare const unlock: () => void;
declare function deliverFile(blob: any, filename: any, mime: any): Promise<void>;
declare function downloadBlob(blob: any, filename: any): void;
declare const GM_OUT: {
    boom: number;
    kick: number;
    snare: number;
    clap: number;
    chat: number;
    ohat: number;
    hitom: number;
    cowbell: number;
};
declare function exportMid(): void;
declare const MIDI_PADS: {
    0: string;
    1: string;
    2: string;
    3: string;
    4: string;
    5: string;
    6: string;
    7: string;
};
declare const midiSupported = true;
declare let midiOn: boolean, midiNames: any[], midiDenied: boolean;
declare function midiStatusLine(): string;
declare function refreshMidiStatus(): void;
declare let hookMidi: () => void;
declare const midiSheet: HTMLElement | null;
declare const midiConnectBtn: HTMLElement | null;
declare const midiExportBtn: any;
declare let midiOpener: any;
declare function openMidiSheet(): void;
declare function closeMidiSheet(): void;
declare const latEl: any;
declare const isDev: boolean;
