console.log('MuzXBox v1.01');
class ZInputDeviceHandler{
	constructor() {
		//
	}
	processKeyboardEvent(keyboardEvent:KeyboardEvent){
		//console.log(keyboardEvent.code);
		if(keyboardEvent.code=='KeyX'){
			this.processKeyX();
		}
		if(keyboardEvent.code=='KeyY'){
			this.processKeyY();
		}
		if(keyboardEvent.code=='KeyA'){
			this.processKeyA();
		}
		if(keyboardEvent.code=='KeyB'){
			this.processKeyB();
		}
		if(keyboardEvent.key=='+'){
			this.processAnyPlus();
		}
		if(keyboardEvent.key=='-'){
			this.processAnyMinus();
		}
		if(keyboardEvent.code=='ArrowLeft'){
			this.processArrowLeft();
		}
		if(keyboardEvent.code=='ArrowRight'){
			this.processArrowRight();
		}
		if(keyboardEvent.code=='ArrowUp'){
			this.processArrowUp();
		}
		if(keyboardEvent.code=='ArrowDown'){
			this.processArrowDown();
		}
	}
	processKeyX(){
		console.log('KeyX');
	}
	processKeyY(){
		console.log('KeyY');
	}
	processKeyA(){
		console.log('KeyA');
	}
	processKeyB(){
		console.log('KeyB');
	}
	processAnyPlus(){
		console.log('+');
	}
	processAnyMinus(){
		console.log('-');
	}
	processArrowLeft(){
		console.log('left');
	}
	processArrowRight(){
		console.log('right');
	}
	processArrowUp(){
		console.log('up');
	}
	processArrowDown(){
		console.log('down');
	}
}

