declare class FxPlayer {
    mp3arrayBuffer: ArrayBuffer | null;
    mp3audioBuffer: AudioBuffer | null;
    currentContext: AudioContext | null;
    mp3sourceNode: AudioBufferSourceNode | null;
    lastStart: number;
    lastDuration: number;
    pitchRatio: number;
    fxShift: FxShift;
    resetSource(): void;
    startAudioBuffer(rebuff: AudioBuffer): void;
    initContext(): void;
    load(file: File): void;
    transpose(): AudioBuffer | null;
}
declare let player: FxPlayer;
declare function startLoadMP3(it: any): void;
declare function warnInit(): void;
declare function onPitchChange(it: any): void;
declare function onCodmpressorLevel(it: any): void;
declare function onCompressorThreshold(it: any): void;
declare function onCompressorKnee(it: any): void;
declare function onCompressorRatio(it: any): void;
declare function onCompressorAttack(it: any): void;
declare function onCompressorRelease(it: any): void;
declare function onReverberatorChange(it: any): void;
declare function onFlangerLevel(it: any): void;
declare function onFlangerDelay(it: any): void;
declare function onFlangerDepth(it: any): void;
declare function onFlangerFeedback(it: any): void;
declare function onFlangerSpeed(it: any): void;
declare function onEq32(it: any): void;
declare function onEq64(it: any): void;
declare function onEq128(it: any): void;
declare function onEq256(it: any): void;
declare function onEq512(it: any): void;
declare function onEq1k(it: any): void;
declare function onEq2k(it: any): void;
declare function onEq4k(it: any): void;
declare function onEq8k(it: any): void;
declare function onEq16k(it: any): void;
declare function resamplePitchShiftFloat32Array(pitchShift: number, numSampsToProcess: number, fftFrameSize: number, osamp: number, sampleRate: number, indata: Float32Array): Float32Array;
declare function ShortTimeFourierTransform(fftBuffer: number[], fftFrameSize: number, sign: number): void;
declare function ___do___PitchShift(audioBuffer: AudioBuffer, ratio: number): void;
declare class FxShift {
    volume: GainNode;
    constructor(currentContext: AudioContext);
    input(): AudioNode;
    output(): AudioNode;
}
